// <auto-generated />
using FootballGroupManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGroupManager.Infrastructure.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260427123411_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calificacion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("PuntajeTotal")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Jugador", b =>
                {
                    b.OwnsOne("FootballGroupManager.Domain.ValueObjects.EstadisticasJugador", "Stats", b1 =>
                        {
                            b1.Property<int>("JugadorId")
                                .HasColumnType("int");

                            b1.Property<int>("Aguante")
                                .HasColumnType("int")
                                .HasColumnName("AGT");

                            b1.Property<int>("Atajada")
                                .HasColumnType("int")
                                .HasColumnName("ATJ");

                            b1.Property<int>("Defensa")
                                .HasColumnType("int")
                                .HasColumnName("DEF");

                            b1.Property<int>("Fisico")
                                .HasColumnType("int")
                                .HasColumnName("FIS");

                            b1.Property<int>("Gambeta")
                                .HasColumnType("int")
                                .HasColumnName("GMB");

                            b1.Property<int>("Pase")
                                .HasColumnType("int")
                                .HasColumnName("PAS");

                            b1.Property<int>("Pegada")
                                .HasColumnType("int")
                                .HasColumnName("PEG");

                            b1.Property<int>("Reflejo")
                                .HasColumnType("int")
                                .HasColumnName("REF");

                            b1.Property<int>("Tiro")
                                .HasColumnType("int")
                                .HasColumnName("TIR");

                            b1.Property<int>("Velocidad")
                                .HasColumnType("int")
                                .HasColumnName("VEL");

                            b1.HasKey("JugadorId");

                            b1.ToTable("Jugadores");

                            b1.WithOwner()
                                .HasForeignKey("JugadorId");
                        });

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
