// <auto-generated />
using System;
using FootballGroupManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGroupManager.Infrastructure.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260428122807_AddUsuariosGruposPartidos")]
    partial class AddUsuariosGruposPartidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("CreadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadorId");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.GrupoUsuario", b =>
                {
                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCapitan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("GrupoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GrupoUsuarios", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaJugado")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.PartidoJugador", b =>
                {
                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("EquipoAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaConfirmacion")
                        .HasColumnType("datetime2");

                    b.HasKey("PartidoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PartidoJugadores", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calificacion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("PuntajeTotal")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Grupo", b =>
                {
                    b.HasOne("FootballGroupManager.Domain.Entities.Usuario", "Creador")
                        .WithMany("GruposCreados")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.GrupoUsuario", b =>
                {
                    b.HasOne("FootballGroupManager.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Miembros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballGroupManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Partido", b =>
                {
                    b.HasOne("FootballGroupManager.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Partidos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.PartidoJugador", b =>
                {
                    b.HasOne("FootballGroupManager.Domain.Entities.Partido", "Partido")
                        .WithMany("Jugadores")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballGroupManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("FootballGroupManager.Domain.ValueObjects.EstadisticasJugador", "Stats", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<int>("Aguante")
                                .HasColumnType("int")
                                .HasColumnName("AGT");

                            b1.Property<int>("Atajada")
                                .HasColumnType("int")
                                .HasColumnName("ATJ");

                            b1.Property<int>("Defensa")
                                .HasColumnType("int")
                                .HasColumnName("DEF");

                            b1.Property<int>("Fisico")
                                .HasColumnType("int")
                                .HasColumnName("FIS");

                            b1.Property<int>("Gambeta")
                                .HasColumnType("int")
                                .HasColumnName("GMB");

                            b1.Property<int>("Pase")
                                .HasColumnType("int")
                                .HasColumnName("PAS");

                            b1.Property<int>("Pegada")
                                .HasColumnType("int")
                                .HasColumnName("PEG");

                            b1.Property<int>("Reflejo")
                                .HasColumnType("int")
                                .HasColumnName("REF");

                            b1.Property<int>("Tiro")
                                .HasColumnType("int")
                                .HasColumnName("TIR");

                            b1.Property<int>("Velocidad")
                                .HasColumnType("int")
                                .HasColumnName("VEL");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Miembros");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("FootballGroupManager.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("GruposCreados");

                    b.Navigation("Membresias");
                });
#pragma warning restore 612, 618
        }
    }
}
